

openapi: 3.0.0
info:
  title: My Module API Documentation
  description: This is a sample API documentation
  version: 1.0.0
  contact:
    name: Bang
    email: ecosystemprogramminglanguage@gmail.com
    url: https://example.com
  license:
    name: Licence name
    url: https://some-url.com
servers:
  - url: http://localhost:8085/api/v1
    description: Local ENV
tags:
  - name: Check
    description: Check
paths:
  /health:
    get:
      summary: Check health
      tags:
        - Check
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                status: Up
      security:
        - jwtAuth: []
components:
  schemas:

  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - jwtAuth: []
